#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <limits>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class SubdividedSlimes {
public:
	int gettot(int M, int S)
	{
		int ans = 0;
		ans += a*b;
	}
	int needCut(int S, int M) {
		if(M > S*(S-1)/2)
			return -1;
		int a = S/2, b = S - a;
		int ans = 0;
		if(ans > M)
			return ans;
		ans += gettot(M-a*b, )
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, int p1, bool hasAnswer, int p2) {
	cout << "Test " << testNum << ": [" << p0 << "," << p1;
	cout << "]" << endl;
	SubdividedSlimes *obj;
	int answer;
	obj = new SubdividedSlimes();
	clock_t startTime = clock();
	answer = obj->needCut(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;
	
	int p0;
	int p1;
	int p2;
	
	// ----- test 0 -----
	disabled = false;
	p0 = 3;
	p1 = 2;
	p2 = 1;
	all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 1 -----
	disabled = false;
	p0 = 3;
	p1 = 3;
	p2 = 2;
	all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 2 -----
	disabled = false;
	p0 = 3;
	p1 = 4;
	p2 = -1;
	all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 3 -----
	disabled = false;
	p0 = 765;
	p1 = 271828;
	p2 = 14;
	all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, true, p2) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// 
// The idols Ami and Mami like playing games.
// Today they bought a new game.
// At the beginning of the game a single slime appears on the screen.
// You are given an int S: the size of the slime.
// 
// The game consists of K turns.
// In each turn of the game the player must choose a single slime and cut it into two smaller parts.
// More precisely, suppose that the player chose a slime of size z.
// When cutting this slime, the player must choose two positive integers x and y such that x+y = z.
// The player will then cut the slime into two smaller slimes.
// The sizes of those smaller slimes will be x and y, respectively.
// Note that the player must always choose a slime of size 2 or more, as it is not possible to cut a slime of size 1.
// 
// The player gets a reward for making each cut:
// whenever you cut a slime of size x+y into slimes of sizes x and y, the player is awarded x*y mascots.
// 
// Ami and Mami have just started a new game.
// You are given two ints S and M.
// Calculate and return the smallest possible K (the number of turns in the game) such that Ami and Mami can get at least M mascots in the game.
// If there exists no such K, return -1 instead.
// 
// 
// DEFINITION
// Class:SubdividedSlimes
// Method:needCut
// Parameters:int, int
// Returns:int
// Method signature:int needCut(int S, int M)
// 
// 
// CONSTRAINTS
// -S will be between 2 and 1000, inclusive.
// -M will be between 1 and 10^9, inclusive.
// 
// 
// EXAMPLES
// 
// 0)
// 3
// 2
// 
// Returns: 1
// 
// There is a single slime of size 3, and the players have to get at least two mascots.
// In this case, K = 1 is sufficient.
// In the only step, cut the only slime into two slimes with sizes 1 and 2.
// (This gives them 1*2 = 2 mascots.)
// 
// 1)
// 3
// 3
// 
// Returns: 2
// 
// There is a single slime of size 3, and the players have to get at least three mascots.
// They can get three mascots in two steps:
// In the first step, cut the only slime into two slimes with sizes 1 and 2.
// (This gives them 1*2 = 2 mascots.)
// In the second step, choose the slime of size 2 and cut it into two slimes of size 1 each.
// (This gives them 1*1 = 1 mascot.)
// The total number of mascots they obtained is 2 + 1 = 3.
// 
// 2)
// 3
// 4
// 
// Returns: -1
// 
// There is a single slime of size 3.
// The players cannot get 4 mascots in any way.
// 
// 3)
// 765
// 271828
// 
// Returns: 14
// 
// 
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit-pf 2.3.0!
